// <auto-generated />
using Cars.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cars.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cars.DAL.Entities.VehicleMakeEntity", b =>
                {
                    b.Property<int>("MakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abrv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("MakeId");

                    b.ToTable("VehicleMakes");

                    b.HasData(
                        new
                        {
                            MakeId = 1,
                            Abrv = "Germany",
                            Name = "Audi"
                        },
                        new
                        {
                            MakeId = 2,
                            Abrv = "Germany",
                            Name = "BMW"
                        },
                        new
                        {
                            MakeId = 3,
                            Abrv = "Japan",
                            Name = "Honda"
                        },
                        new
                        {
                            MakeId = 4,
                            Abrv = "Italy",
                            Name = "Alfa Romeo"
                        },
                        new
                        {
                            MakeId = 5,
                            Abrv = "Spain",
                            Name = "Seat"
                        },
                        new
                        {
                            MakeId = 6,
                            Abrv = "Japan",
                            Name = "Subaru"
                        });
                });

            modelBuilder.Entity("Cars.DAL.Entities.VehicleModelEntity", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abrv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MakeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("ModelId");

                    b.HasIndex("MakeId");

                    b.ToTable("VehicleModels");

                    b.HasData(
                        new
                        {
                            ModelId = 1,
                            Abrv = "Germany",
                            MakeId = 1,
                            Name = "A3"
                        },
                        new
                        {
                            ModelId = 2,
                            Abrv = "Germany",
                            MakeId = 1,
                            Name = "A6"
                        },
                        new
                        {
                            ModelId = 3,
                            Abrv = "Germany",
                            MakeId = 2,
                            Name = "M3"
                        },
                        new
                        {
                            ModelId = 4,
                            Abrv = "Germany",
                            MakeId = 2,
                            Name = "530"
                        },
                        new
                        {
                            ModelId = 5,
                            Abrv = "Spain",
                            MakeId = 5,
                            Name = "Leon"
                        },
                        new
                        {
                            ModelId = 6,
                            Abrv = "Japan",
                            MakeId = 3,
                            Name = "Civic"
                        });
                });

            modelBuilder.Entity("Cars.DAL.Entities.VehicleModelEntity", b =>
                {
                    b.HasOne("Cars.DAL.Entities.VehicleMakeEntity", "VehicleMake")
                        .WithMany("VehicleModelEntities")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
